### ISSUE TITLE
Why don't split playbook to correct roles?

### ISSUE THREAD

**Issue by Nklya** [sadsfae/ansible-nagios#21]
Hello.
First of all, I want to say thank you for this useful playbook.

But I have a question. Why don't you split this playbook to correct separate roles?

**Comment by sadsfae** [comment]
Hi @Nklya we do split out ```nagios``` and ```nagios-client```, the latter is pulled in when a specific kind of check requires (or is more advantageous to use) NRPE and report the results.

Is this what you mean, or are you referring to splitting out each kind of server/service/host category into its own role?  If so I found it easier to maintain by expanding out the jinja2 templates rather than roles.

I could be convinced otherwise however.

**Comment by Nklya** [comment]
Yes, I meant split out nagios and nagios-client.
For now, I split them myself for use into my project.

**Comment by sadsfae** [comment]
Ah yes, combining them (when needed) is purposeful.  The reason is that I'd rather scale out the service and host checks than explicitly separate NRPE and generic Nagios -> hosts checks.  

This is because it's not always manageable at a large scale to check everything outbound (nor can you for some things like internal APIs) for some services or specific types of servers, as a result I'll sometimes use a combination of generic Nagios checks (TCP/port, HTTP, ICMP) but also use internal NRPE checks and batch those up and send the results back.  I hope that better explains the reasoning.

If I have 10 servers or even 100 servers I can probably check things directly from the Nagios server, but if I have 1,000 or 5,000 servers it becomes an issue in which case it's better to rely on batched up responses from multiple service checks via one NRPE check-in than rely on Nagios pinging out across a large fleet of servers for each service check.
