### ISSUE TITLE
Working with large number of hosts

### ISSUE THREAD

**Issue by jmreicha** [sadsfae/ansible-nagios#28]
Great work on this project.  I'm trying to get this working with a largish number of servers and running into some issues.  From my understanding, for this method to work it needs to gather facts for all servers, which can take quite some time and I've been finding issues if a server can't be connected to.

Are there any good ways to speed things up or work around the fact gathering?

**Comment by sadsfae** [comment]
> Great work on this project. I'm trying to get this working with a largish number of servers and running into some issues. From my understanding, for this method to work it needs to gather facts for all servers, which can take quite some time and I've been finding issues if a server can't be connected to.
> 
> Are there any good ways to speed things up or work around the fact gathering?

Hey @jmreicha sorry for the late reply.  Fact gathering is indeed going to be required for full functionality.

You can look into [using the Ansible cache plugin for this.](https://docs.ansible.com/ansible/latest/plugins/cache.html)  That should make a tremendous difference with lots of hosts and is highly recommended.

One other workaround here is to use the `[oobservers]` inventory group for systems that are problematic to fact gathering.  This provides only base ping, ssh and http checks on them.  You could also toss these into `[switches]` inventory group instead (just ping, ssh).  Just keep in mind that each device/server entry can only belong to one inventory group.

Keep in mind for these two categories of systems since there is no fact generation you'll need to tell ansible the IP address of them.

e.g.

```
[oobservers]
slowhost01 ansible_host=10.1.20.222
slowhost02 ansible_host=10.1.20.223

[switches]
slowhost03 ansible_host=10.1.20.224
slowhost04 ansible_host=10.1.20.225
```

With the latter you obviously don't get the full functionality and all the checks you'd probably want.

If there's interest I can make a "no facts" inventory group that provides just bare-bones ping/ssh checks instead of abusing the `[switches]` and `[oobservers]` groups.
