### ISSUE TITLE
Add new hosts

### ISSUE THREAD

**Issue by Noname2244** [sadsfae/ansible-nagios#30]
Can you add a bunch of hosts to the already installed nagios?

**Comment by sadsfae** [comment]
hey @Noname2244 for sure, all that's required is you put them under the proper Ansible inventory section.  Remember that a host can only belong to one inventory section due to the way the config templates are generated.

e.g. You started with:

```
[servers]
server01
server02
```

To add more hosts just shove more after `server02` in the example and re-run the playbook.
