### ISSUE TITLE
Add Same server in Multiple group

### ISSUE THREAD

**Issue by chetanpatangade** [sadsfae/ansible-nagios#8]
Hi,

I downloaded this module, but I have one query.  If i add same server in multiple groups it should be run.
For eg I added one server [10.1.2.86] in  [switches][webservers] [servers] Group. I am thinking that it would use the checks that we have mentioned in [switches][webservers] [servers] i.e. in Nagios My server will be like this :- 10.1.2.86 : [switches] :- All Checks
                                  [webservers] All Checks
                                  [servers] All Checks

How can it be done ? Can you please give any suggestion ?

**Comment by chetanpatangade** [comment]
Any update on this ?

**Comment by chetanpatangade** [comment]
Any update on this ?

**Comment by sadsfae** [comment]
Hi @chetanpatangade 

The way this is templated you should be adding a server (or device) only to _one type_ of hostgroup or as it parses the inventory file - one group only that matches the purpose.

For example a generic Linux server should _only_ be added to the ```[servers]``` inventory group in ```hosts```

```
[servers]
your-server-hostname
```

Don't put it in other categories as Ansible will pick the first occurrence of it due to how it's written and parsed by nagios.

If this server is also a webserver then just place it in the ```[webservers]``` group.  It will still inherit the same checks as ```[servers]``` with the inclusion of HTTP checks.

```
[webservers]
my-web-server01
```

If you have a generic switch that needs checks for ssh, ping

```
[switches]
my-switch-hostname ansible_host=10.1.2.88
```

If you have a generic out-of-band interface that needs ssh, ping, http checks

```
[oobservers]
my-ipmi-interface-server01 ansible_host=10.2.1.88
```

**Note:** You only need to specify the IP address via ```ansible_host``` for devices that are not standard Linux servers and cannot run the NRPE Nagios client (and Python and Ansible facts discovery).

**Comment by sadsfae** [comment]
Closing this now, I hope this answers your query.  If not please re-open.
